#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — GT-01 exact Git Town v24.0.0 host admission receipt (issue #15).
#
# This wizard measures everything measurable and asks only for the decisions
# issue #15 defers to a human. A lane the human does not decide is recorded as
# NOT_EXERCISED — never defaulted to PASS. The admission result is PASS only
# when every repository-required lane is PASS.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# Answers persist outside the repository so a re-run resumes without leaving
# untracked clutter in the tree.
ENV_FILE="${TMPDIR:-/tmp}/git-town-admission-answers.env"

# Policy pins, re-read from docs/git/REPO_PROFILE.md in stage 1 rather than
# trusted from these copies.
REQUIRED_VERSION="v24.0.0"
UPSTREAM_REPO="git-town/git-town"
RELEASE_ID="358702660"
TAG_COMMIT="0f3e55f5a6bae5b319dd713a0606263d0551af66"
MANIFEST_SHA256="7532377166cb59dc01c74f86e3a71c54ba9567a461313a5d203a1ea99c571b24"

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
RECEIPT_DIR="${REPO_ROOT}/receipts/git-town/admission"
WORK_DIR="$(mktemp -d)"
LANES_FILE="${WORK_DIR}/lanes.tsv"
: > "$LANES_FILE"

# The work directory is deliberately left in place. Downloaded artifacts and
# the lane ledger are evidence; this wizard does not delete evidence, and the
# operating system reclaims the temp directory on its own schedule.

# record_lane NAME STATE DETAIL — append one evidence lane. STATE is PASS,
# FAIL or NOT_EXERCISED; nothing else may be written.
record_lane() {
  case "$2" in
    PASS|FAIL|NOT_EXERCISED) ;;
    *) printf 'internal error: bad lane state %s\n' "$2" >&2; exit 1 ;;
  esac
  printf '%s\t%s\t%s\n' "$1" "$2" "$3" >> "$LANES_FILE"
  case "$2" in
    PASS) printf '  %s✓ %s%s  %s\n' "$GREEN" "$1" "$RESET" "$3" ;;
    FAIL) printf '  %s✗ %s%s  %s\n' "$RED" "$1" "$RESET" "$3" ;;
    *)    printf '  %s· %s%s  %s\n' "$YELLOW" "$1" "$RESET" "$3" ;;
  esac
}

sha256_of() {
  if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | awk '{print $1}'
  else sha256sum "$1" | awk '{print $1}'; fi
}

banner "GT-01 · Git Town ${REQUIRED_VERSION} host admission"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Repository identity and policy pins"
say "Re-reading the pins from docs/git/REPO_PROFILE.md rather than trusting the"
say "copies inside this script. If they have drifted, this wizard stops."
PROFILE="${REPO_ROOT}/docs/git/REPO_PROFILE.md"
if [[ ! -f "$PROFILE" ]]; then
  printf '  %sSTOP%s  docs/git/REPO_PROFILE.md is absent; run this from the repository.\n' "$RED" "$RESET"
  exit 1
fi
for pin in "required_version: ${REQUIRED_VERSION}" \
           "source_repository: ${UPSTREAM_REPO}" \
           "release_id: ${RELEASE_ID}" \
           "immutable_tag_commit: ${TAG_COMMIT}" \
           "checksums_manifest_sha256: ${MANIFEST_SHA256}"; do
  if grep -qF "$pin" "$PROFILE"; then
    say "  matches profile: ${pin}"
  else
    printf '  %sSTOP%s  the profile no longer pins: %s\n' "$RED" "$RESET" "$pin"
    say "This wizard is out of date with the repository. Reconcile them first."
    exit 1
  fi
done
record_lane "repository_policy_pins" "PASS" "profile agrees with every pin this wizard uses"
pause "Pins agree. Continue?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Host platform and architecture"
HOST_OS="$(uname -s)"; HOST_ARCH="$(uname -m)"
case "$HOST_OS" in
  Darwin)  ASSET_OS="macos" ;;
  Linux)   ASSET_OS="linux" ;;
  FreeBSD) ASSET_OS="freebsd" ;;
  NetBSD)  ASSET_OS="netbsd" ;;
  *)       ASSET_OS="" ;;
esac
case "$HOST_ARCH" in
  arm64|aarch64) ASSET_ARCH="arm" ;;
  x86_64|amd64)  ASSET_ARCH="intel" ;;
  *)             ASSET_ARCH="" ;;
esac
say "Detected: ${HOST_OS} / ${HOST_ARCH}"
if [[ -z "$ASSET_OS" || -z "$ASSET_ARCH" ]]; then
  record_lane "host_platform_architecture" "NOT_EXERCISED" "unrecognized host ${HOST_OS}/${HOST_ARCH}"
  say "This host does not map to a published artifact, so the platform lane"
  say "stays NOT_EXERCISED and admission cannot pass on this machine."
else
  record_lane "host_platform_architecture" "PASS" "${HOST_OS}/${HOST_ARCH} maps to ${ASSET_OS}_${ASSET_ARCH}"
  say "Matching release artifact: git-town_${ASSET_OS}_${ASSET_ARCH}_64.tar.gz"
fi
pause "Continue?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Name the acquisition method  ·  HUMAN DECISION"
say "Issue #15 is blocked until a human names how this host acquires the"
say "artifact. The repository deliberately does not guess it."
say ""
step "Open the immutable release and look at its assets."
open_url "https://github.com/${UPSTREAM_REPO}/releases/tag/${REQUIRED_VERSION}"
say ""
say "Live asset list for release ${RELEASE_ID}:"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh api "/repos/${UPSTREAM_REPO}/releases/${RELEASE_ID}" --jq '.assets[].name' 2>/dev/null | sed 's/^/    /' \
    || say "    (could not list assets; read them in the browser)"
else
  say "    (gh unavailable; read them in the browser)"
fi
say ""
say "A mutable selector such as 'latest' is refused by policy. Name the exact"
say "asset from the pinned release, or answer SKIP to leave this NOT_EXERCISED."
ask ACQUISITION_ASSET "Exact asset filename (or SKIP):"
ask ACQUISITION_OWNER "Who is naming this acquisition method? (name/handle, or SKIP):"
if [[ -z "$ACQUISITION_ASSET" || "$ACQUISITION_ASSET" == "SKIP" \
   || -z "$ACQUISITION_OWNER" || "$ACQUISITION_OWNER" == "SKIP" ]]; then
  ACQUISITION_ASSET=""; ACQUISITION_OWNER=""
  record_lane "artifact_acquisition" "NOT_EXERCISED" "no human named the acquisition method"
else
  write_env ACQUISITION_ASSET "$ACQUISITION_ASSET"
  write_env ACQUISITION_OWNER "$ACQUISITION_OWNER"
  record_lane "artifact_acquisition" "PASS" \
    "immutable release ${RELEASE_ID} asset ${ACQUISITION_ASSET}, named by ${ACQUISITION_OWNER}"
fi
pause "Continue?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Checksums manifest"
EXPECTED_SHA=""
if [[ -z "$ACQUISITION_ASSET" ]]; then
  record_lane "checksums_manifest" "NOT_EXERCISED" "no acquisition method named"
else
  say "Downloading checksums.txt from the pinned release and verifying it"
  say "against the digest the repository pinned."
  MANIFEST="${WORK_DIR}/checksums.txt"
  if curl -fsSL "https://github.com/${UPSTREAM_REPO}/releases/download/${REQUIRED_VERSION}/checksums.txt" -o "$MANIFEST"; then
    GOT="$(sha256_of "$MANIFEST")"
    if [[ "$GOT" == "$MANIFEST_SHA256" ]]; then
      record_lane "checksums_manifest" "PASS" "manifest digest matches the pinned value"
    else
      record_lane "checksums_manifest" "FAIL" "manifest digest ${GOT} does not match the pin"
      say "The manifest does not match the pin. Investigate before continuing."
      confirm "Continue anyway and record the FAIL?" || exit 1
    fi
    EXPECTED_SHA="$(awk -v a="$ACQUISITION_ASSET" '$2 == a {print $1}' "$MANIFEST")"
    if [[ -n "$EXPECTED_SHA" ]]; then
      say "Manifest expects ${ACQUISITION_ASSET} → ${EXPECTED_SHA}"
    else
      say "The manifest has no line for ${ACQUISITION_ASSET}."
    fi
  else
    record_lane "checksums_manifest" "NOT_EXERCISED" "could not download the manifest"
  fi
fi
pause "Continue?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Artifact download and digest"
ARTIFACT_SHA=""
if [[ -z "$EXPECTED_SHA" ]]; then
  record_lane "artifact_sha256" "NOT_EXERCISED" "no manifest line to verify against"
else
  ARTIFACT="${WORK_DIR}/${ACQUISITION_ASSET}"
  say "Downloading ${ACQUISITION_ASSET} from the pinned release…"
  if curl -fsSL "https://github.com/${UPSTREAM_REPO}/releases/download/${REQUIRED_VERSION}/${ACQUISITION_ASSET}" -o "$ARTIFACT"; then
    ARTIFACT_SHA="$(sha256_of "$ARTIFACT")"
    if [[ "$ARTIFACT_SHA" == "$EXPECTED_SHA" ]]; then
      record_lane "artifact_sha256" "PASS" "${ARTIFACT_SHA}"
    else
      record_lane "artifact_sha256" "FAIL" "downloaded ${ARTIFACT_SHA}, manifest expects ${EXPECTED_SHA}"
      ARTIFACT_SHA=""
    fi
  else
    record_lane "artifact_sha256" "NOT_EXERCISED" "download failed"
  fi
fi
pause "Continue?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Installed executable digest and version"
EXECUTABLE_SHA=""; VERSION_OUTPUT=""; BIN=""
if [[ -z "$ARTIFACT_SHA" ]]; then
  record_lane "installed_executable_sha256" "NOT_EXERCISED" "no digest-verified artifact"
  record_lane "executable_version_output" "NOT_EXERCISED" "no digest-verified artifact"
else
  say "Extracting into a scratch directory. Nothing is installed system-wide,"
  say "and no binary is committed — issue #15 forbids committing the executable."
  EXTRACT="${WORK_DIR}/extract"; mkdir -p "$EXTRACT"
  if tar -xzf "${WORK_DIR}/${ACQUISITION_ASSET}" -C "$EXTRACT" 2>/dev/null; then
    BIN="$(find "$EXTRACT" -type f -name 'git-town' -perm -u+x 2>/dev/null | head -1)"
    if [[ -n "$BIN" ]]; then
      EXECUTABLE_SHA="$(sha256_of "$BIN")"
      record_lane "installed_executable_sha256" "PASS" "${EXECUTABLE_SHA}"
      VERSION_OUTPUT="$("$BIN" --version 2>&1 | head -1 || true)"
      say "Version output: ${VERSION_OUTPUT}"
      if printf '%s' "$VERSION_OUTPUT" | grep -qF "${REQUIRED_VERSION#v}"; then
        record_lane "executable_version_output" "PASS" "${VERSION_OUTPUT}"
      else
        record_lane "executable_version_output" "FAIL" "does not resolve to ${REQUIRED_VERSION}: ${VERSION_OUTPUT}"
      fi
    else
      record_lane "installed_executable_sha256" "NOT_EXERCISED" "no git-town executable inside the artifact"
      record_lane "executable_version_output" "NOT_EXERCISED" "no executable to run"
    fi
  else
    record_lane "installed_executable_sha256" "NOT_EXERCISED" "could not extract the artifact"
    record_lane "executable_version_output" "NOT_EXERCISED" "could not extract the artifact"
  fi
fi
pause "Continue?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Repository configuration compatibility"
if [[ -n "$BIN" && -f "${REPO_ROOT}/.git-town.toml" ]]; then
  if ( cd "$REPO_ROOT" && "$BIN" config >/dev/null 2>&1 ); then
    record_lane "repository_config_compatibility" "PASS" ".git-town.toml parses under the admitted executable"
  else
    record_lane "repository_config_compatibility" "FAIL" "the admitted executable could not read .git-town.toml"
  fi
else
  record_lane "repository_config_compatibility" "NOT_EXERCISED" "no admitted executable to parse the config"
fi
pause "Continue?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "SBOM / transitive dependency review  ·  HUMAN DECISION"
say "The direct MIT license is one input and is already reviewed. The"
say "transitive dependency position is a separate lane needing a named owner."
say ""
step "Review the module graph for ${REQUIRED_VERSION}."
open_url "https://github.com/${UPSTREAM_REPO}/blob/${REQUIRED_VERSION}/go.mod"
ask SBOM_OWNER "Who owns the SBOM/transitive review? (name/handle, or SKIP):"
if [[ -z "$SBOM_OWNER" || "$SBOM_OWNER" == "SKIP" ]]; then
  record_lane "sbom_or_transitive_review" "NOT_EXERCISED" "no named owner"
else
  ask SBOM_DECISION "Their decision — type ACCEPTED or REJECTED:"
  case "$SBOM_DECISION" in
    ACCEPTED) write_env SBOM_OWNER "$SBOM_OWNER"
              record_lane "sbom_or_transitive_review" "PASS" "accepted by ${SBOM_OWNER}" ;;
    REJECTED) record_lane "sbom_or_transitive_review" "FAIL" "rejected by ${SBOM_OWNER}" ;;
    *)        record_lane "sbom_or_transitive_review" "NOT_EXERCISED" "no decision recorded by ${SBOM_OWNER}" ;;
  esac
fi
pause "Continue?"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Required notices review  ·  HUMAN DECISION"
step "Review the notices and attribution obligations for ${REQUIRED_VERSION}."
open_url "https://github.com/${UPSTREAM_REPO}/blob/${REQUIRED_VERSION}/LICENSE"
ask NOTICES_OWNER "Who owns the required-notices review? (name/handle, or SKIP):"
if [[ -z "$NOTICES_OWNER" || "$NOTICES_OWNER" == "SKIP" ]]; then
  record_lane "required_notices_review" "NOT_EXERCISED" "no named owner"
else
  ask NOTICES_DECISION "Their decision — type ACCEPTED or REJECTED:"
  case "$NOTICES_DECISION" in
    ACCEPTED) write_env NOTICES_OWNER "$NOTICES_OWNER"
              record_lane "required_notices_review" "PASS" "accepted by ${NOTICES_OWNER}" ;;
    REJECTED) record_lane "required_notices_review" "FAIL" "rejected by ${NOTICES_OWNER}" ;;
    *)        record_lane "required_notices_review" "NOT_EXERCISED" "no decision recorded by ${NOTICES_OWNER}" ;;
  esac
fi
pause "Continue?"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Organization / legal approval  ·  HUMAN DECISION"
say "Tool presence, a version string, and the direct MIT license are not legal"
say "approval. This lane needs a person to accept the terms for this exact"
say "release and artifact."
ask LEGAL_OWNER "Who is accepting on behalf of the organization? (name/handle, or SKIP):"
if [[ -z "$LEGAL_OWNER" || "$LEGAL_OWNER" == "SKIP" ]]; then
  record_lane "organization_legal_approval" "NOT_EXERCISED" "no named approver"
else
  say "Approval binds release ${RELEASE_ID}, tag commit ${TAG_COMMIT},"
  say "artifact ${ACQUISITION_ASSET:-<none named>}."
  ask LEGAL_DECISION "Their decision — type APPROVED or REFUSED:"
  case "$LEGAL_DECISION" in
    APPROVED) write_env LEGAL_OWNER "$LEGAL_OWNER"
              record_lane "organization_legal_approval" "PASS" "approved by ${LEGAL_OWNER} for release ${RELEASE_ID}" ;;
    REFUSED)  record_lane "organization_legal_approval" "FAIL" "refused by ${LEGAL_OWNER}" ;;
    *)        record_lane "organization_legal_approval" "NOT_EXERCISED" "no decision recorded by ${LEGAL_OWNER}" ;;
  esac
fi

# ── Receipt ───────────────────────────────────────────────────────────────
record_lane "direct_license_identity" "PASS" "MIT text reviewed; digest pinned in docs/git/REPO_PROFILE.md"

mkdir -p "$RECEIPT_DIR"
RECEIPT_PATH="$(
  REQUIRED_VERSION="$REQUIRED_VERSION" UPSTREAM_REPO="$UPSTREAM_REPO" \
  RELEASE_ID="$RELEASE_ID" TAG_COMMIT="$TAG_COMMIT" \
  ARTIFACT_NAME="${ACQUISITION_ASSET:-}" ARTIFACT_SHA="${ARTIFACT_SHA:-}" \
  EXECUTABLE_SHA="${EXECUTABLE_SHA:-}" VERSION_OUTPUT="${VERSION_OUTPUT:-}" \
  HOST_OS="$HOST_OS" HOST_ARCH="$HOST_ARCH" \
  LANES_FILE="$LANES_FILE" RECEIPT_DIR="$RECEIPT_DIR" \
  python3 "${REPO_ROOT}/scripts/git-town/admission_receipt.py"
)"

_clear
printf '\n%s%s  GT-01 admission receipt written%s\n\n' "$BOLD" "$BLUE" "$RESET"
say "${RECEIPT_PATH#"${REPO_ROOT}/"}"
printf '\n'
# The receipt reader lives in the Python module, not in an inline snippet:
# quoting a nested f-string through the shell is how the previous version of
# this block shipped a SyntaxError that only fired on the blocked path.
RESULT="$(python3 "${REPO_ROOT}/scripts/git-town/admission_receipt.py" --result "$RECEIPT_PATH")"
if [[ "$RESULT" == "PASS" ]]; then
  printf '  %sADMISSION RESULT: PASS%s\n\n' "$GREEN" "$RESET"
  say "Every required lane passed. Point HOST_GIT_TOWN_BIN at the executable,"
  say "update docs/git/REPO_PROFILE.md and docs/git/GIT_TOWN_ADMISSION.md from"
  say "this receipt, then close issue #15."
else
  printf '  %sADMISSION RESULT: %s%s\n\n' "$YELLOW" "$RESULT" "$RESET"
  say "At least one required lane is not PASS. Still open:"
  python3 "${REPO_ROOT}/scripts/git-town/admission_receipt.py" --explain "$RECEIPT_PATH"
  say ""
  say "Re-run after those decisions are made; answers already given are kept."
fi
printf '\n'
say "The receipt is read-only and content-addressed. It records digests only —"
say "no absolute host paths, no credentials, no executable bytes."
say "Downloaded artifacts and the lane ledger are left in ${WORK_DIR}"
say "as evidence; this wizard deletes nothing."
printf '\n'
